# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Git\Python\douyinMaster\main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(885, 684)
        Dialog.setMinimumSize(QtCore.QSize(640, 480))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/pic/douyin.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_ActKey = QtWidgets.QPushButton(self.tab)
        self.pushButton_ActKey.setObjectName("pushButton_ActKey")
        self.gridLayout_3.addWidget(self.pushButton_ActKey, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_EmulatorLocation = QtWidgets.QPushButton(self.tab)
        self.pushButton_EmulatorLocation.setObjectName("pushButton_EmulatorLocation")
        self.gridLayout_3.addWidget(self.pushButton_EmulatorLocation, 6, 2, 1, 1)
        self.label_LicenseAvaliable = QtWidgets.QLabel(self.tab)
        self.label_LicenseAvaliable.setText("")
        self.label_LicenseAvaliable.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LicenseAvaliable.setObjectName("label_LicenseAvaliable")
        self.gridLayout_3.addWidget(self.label_LicenseAvaliable, 2, 1, 1, 1)
        self.pushButton_DownloadEmulator = QtWidgets.QPushButton(self.tab)
        self.pushButton_DownloadEmulator.setObjectName("pushButton_DownloadEmulator")
        self.gridLayout_3.addWidget(self.pushButton_DownloadEmulator, 3, 1, 1, 1)
        self.pushButton_DownloadDouyin = QtWidgets.QPushButton(self.tab)
        self.pushButton_DownloadDouyin.setObjectName("pushButton_DownloadDouyin")
        self.gridLayout_3.addWidget(self.pushButton_DownloadDouyin, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.pushButton_StartEmulator = QtWidgets.QPushButton(self.tab)
        self.pushButton_StartEmulator.setObjectName("pushButton_StartEmulator")
        self.gridLayout_3.addWidget(self.pushButton_StartEmulator, 6, 1, 1, 1)
        self.pushButton_LicenseCheck = QtWidgets.QPushButton(self.tab)
        self.pushButton_LicenseCheck.setObjectName("pushButton_LicenseCheck")
        self.gridLayout_3.addWidget(self.pushButton_LicenseCheck, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.lineEdit_License = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_License.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_License.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_License.setObjectName("lineEdit_License")
        self.gridLayout_3.addWidget(self.lineEdit_License, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 5, 2, 1, 1)
        self.pushButton_EmulatorConfig = QtWidgets.QPushButton(self.tab)
        self.pushButton_EmulatorConfig.setObjectName("pushButton_EmulatorConfig")
        self.gridLayout_3.addWidget(self.pushButton_EmulatorConfig, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 6, 0, 1, 1)
        self.lineEdit_PhoneNumber = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_PhoneNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PhoneNumber.setObjectName("lineEdit_PhoneNumber")
        self.gridLayout_3.addWidget(self.lineEdit_PhoneNumber, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.checkBox_Cnt = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_Cnt.setObjectName("checkBox_Cnt")
        self.gridLayout_2.addWidget(self.checkBox_Cnt, 16, 0, 1, 1)
        self.label_DownVideo = QtWidgets.QLabel(self.tab_2)
        self.label_DownVideo.setText("")
        self.label_DownVideo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_DownVideo.setObjectName("label_DownVideo")
        self.gridLayout_2.addWidget(self.label_DownVideo, 10, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 3, 1, 1)
        self.checkBox_DownVideo = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_DownVideo.setObjectName("checkBox_DownVideo")
        self.gridLayout_2.addWidget(self.checkBox_DownVideo, 10, 0, 1, 1)
        self.checkBox_AutoAwesome = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoAwesome.setChecked(True)
        self.checkBox_AutoAwesome.setObjectName("checkBox_AutoAwesome")
        self.gridLayout_2.addWidget(self.checkBox_AutoAwesome, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.comboBox_WorkMode = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_WorkMode.setObjectName("comboBox_WorkMode")
        self.comboBox_WorkMode.addItem("")
        self.comboBox_WorkMode.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_WorkMode, 4, 2, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 15, 2, 1, 1)
        self.comboBox_WatchTime = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_WatchTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_WatchTime.setObjectName("comboBox_WatchTime")
        self.comboBox_WatchTime.addItem("")
        self.comboBox_WatchTime.addItem("")
        self.comboBox_WatchTime.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_WatchTime, 6, 2, 1, 1)
        self.pushButton_InitDevice = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_InitDevice.setObjectName("pushButton_InitDevice")
        self.gridLayout_2.addWidget(self.pushButton_InitDevice, 3, 0, 1, 1)
        self.checkBox_AutoAddFriend = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoAddFriend.setChecked(True)
        self.checkBox_AutoAddFriend.setObjectName("checkBox_AutoAddFriend")
        self.gridLayout_2.addWidget(self.checkBox_AutoAddFriend, 9, 0, 1, 1)
        self.label_ResartDouyin = QtWidgets.QLabel(self.tab_2)
        self.label_ResartDouyin.setText("")
        self.label_ResartDouyin.setObjectName("label_ResartDouyin")
        self.gridLayout_2.addWidget(self.label_ResartDouyin, 5, 2, 1, 2)
        self.checkBox_AutoComment = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoComment.setObjectName("checkBox_AutoComment")
        self.gridLayout_2.addWidget(self.checkBox_AutoComment, 13, 0, 1, 1)
        self.pushButton_Run = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.gridLayout_2.addWidget(self.pushButton_Run, 3, 2, 1, 2)
        self.checkBox_RestartDouyin = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_RestartDouyin.setChecked(True)
        self.checkBox_RestartDouyin.setObjectName("checkBox_RestartDouyin")
        self.gridLayout_2.addWidget(self.checkBox_RestartDouyin, 5, 0, 1, 1)
        self.comboBox_RandomStrLen = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_RandomStrLen.setObjectName("comboBox_RandomStrLen")
        self.comboBox_RandomStrLen.addItem("")
        self.comboBox_RandomStrLen.addItem("")
        self.comboBox_RandomStrLen.addItem("")
        self.comboBox_RandomStrLen.addItem("")
        self.comboBox_RandomStrLen.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_RandomStrLen, 15, 3, 1, 1)
        self.textEdit_Comment = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_Comment.setObjectName("textEdit_Comment")
        self.gridLayout_2.addWidget(self.textEdit_Comment, 13, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 12, 2, 1, 1)
        self.comboBox_CommentType = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_CommentType.setObjectName("comboBox_CommentType")
        self.comboBox_CommentType.addItem("")
        self.comboBox_CommentType.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_CommentType, 12, 3, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_OnlinePeople = QtWidgets.QLabel(Dialog)
        self.label_OnlinePeople.setText("")
        self.label_OnlinePeople.setObjectName("label_OnlinePeople")
        self.gridLayout.addWidget(self.label_OnlinePeople, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textEdit_Print = QtWidgets.QTextEdit(Dialog)
        self.textEdit_Print.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit_Print.setAcceptDrops(True)
        self.textEdit_Print.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_Print.setObjectName("textEdit_Print")
        self.verticalLayout.addWidget(self.textEdit_Print)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_SaveLog = QtWidgets.QPushButton(Dialog)
        self.pushButton_SaveLog.setObjectName("pushButton_SaveLog")
        self.horizontalLayout_2.addWidget(self.pushButton_SaveLog)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_ClearLog = QtWidgets.QPushButton(Dialog)
        self.pushButton_ClearLog.setObjectName("pushButton_ClearLog")
        self.horizontalLayout_2.addWidget(self.pushButton_ClearLog)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "[耐诺网络]抖音大师 v1.0"))
        self.pushButton_ActKey.setText(_translate("Dialog", "激活"))
        self.label_2.setText(_translate("Dialog", "手机号码"))
        self.pushButton_EmulatorLocation.setText(_translate("Dialog", "路径设置"))
        self.pushButton_DownloadEmulator.setText(_translate("Dialog", "下载模拟器"))
        self.pushButton_DownloadDouyin.setText(_translate("Dialog", "下载抖音"))
        self.label_20.setText(_translate("Dialog", "第一步"))
        self.pushButton_StartEmulator.setText(_translate("Dialog", "启动模拟器"))
        self.pushButton_LicenseCheck.setText(_translate("Dialog", "检查"))
        self.label_18.setText(_translate("Dialog", "有效期"))
        self.lineEdit_License.setText(_translate("Dialog", "d0ced2fa-496d-11e8-869d-d46d6d9832e8"))
        self.label_21.setText(_translate("Dialog", "第二步"))
        self.label_4.setText(_translate("Dialog", "序列号"))
        self.pushButton.setText(_translate("Dialog", "如何安装"))
        self.pushButton_EmulatorConfig.setText(_translate("Dialog", "配置教程"))
        self.label_3.setText(_translate("Dialog", "第三步"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "初始化"))
        self.label_5.setText(_translate("Dialog", "每段视频观看时间："))
        self.checkBox_Cnt.setText(_translate("Dialog", "显示计数"))
        self.label_6.setText(_translate("Dialog", "秒（尽量不要太短）"))
        self.checkBox_DownVideo.setText(_translate("Dialog", "自动下载视频"))
        self.checkBox_AutoAwesome.setText(_translate("Dialog", "自动点赞"))
        self.label.setText(_translate("Dialog", "工作模式："))
        self.comboBox_WorkMode.setItemText(0, _translate("Dialog", "默认模式"))
        self.comboBox_WorkMode.setItemText(1, _translate("Dialog", "只刷关注用户"))
        self.checkBox.setText(_translate("Dialog", "结尾插入随机符长度"))
        self.comboBox_WatchTime.setCurrentText(_translate("Dialog", "0-5"))
        self.comboBox_WatchTime.setItemText(0, _translate("Dialog", "0-5"))
        self.comboBox_WatchTime.setItemText(1, _translate("Dialog", "5-10"))
        self.comboBox_WatchTime.setItemText(2, _translate("Dialog", "10-15"))
        self.pushButton_InitDevice.setText(_translate("Dialog", "初始化模拟器"))
        self.checkBox_AutoAddFriend.setText(_translate("Dialog", "自动加好友"))
        self.checkBox_AutoComment.setText(_translate("Dialog", "自动评论"))
        self.pushButton_Run.setText(_translate("Dialog", "开始"))
        self.checkBox_RestartDouyin.setText(_translate("Dialog", "自动重启抖音"))
        self.comboBox_RandomStrLen.setItemText(0, _translate("Dialog", "4"))
        self.comboBox_RandomStrLen.setItemText(1, _translate("Dialog", "5"))
        self.comboBox_RandomStrLen.setItemText(2, _translate("Dialog", "6"))
        self.comboBox_RandomStrLen.setItemText(3, _translate("Dialog", "7"))
        self.comboBox_RandomStrLen.setItemText(4, _translate("Dialog", "8"))
        self.label_8.setText(_translate("Dialog", "评论内容（一行一条）："))
        self.comboBox_CommentType.setItemText(0, _translate("Dialog", "随机评论"))
        self.comboBox_CommentType.setItemText(1, _translate("Dialog", "顺序评论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "一键操作"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "帮助说明"))
        self.label_9.setText(_translate("Dialog", "当前在线人数："))
        self.pushButton_SaveLog.setText(_translate("Dialog", "保存日志"))
        self.pushButton_ClearLog.setText(_translate("Dialog", "清除"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

