# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Git\Python\douyinMaster\main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(906, 699)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/pic/douyin.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_StartEmulator = QtWidgets.QPushButton(self.tab)
        self.pushButton_StartEmulator.setObjectName("pushButton_StartEmulator")
        self.gridLayout_3.addWidget(self.pushButton_StartEmulator, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.pushButton_VisitHome = QtWidgets.QPushButton(self.tab)
        self.pushButton_VisitHome.setObjectName("pushButton_VisitHome")
        self.gridLayout_3.addWidget(self.pushButton_VisitHome, 0, 1, 1, 1)
        self.pushButton_ActKey = QtWidgets.QPushButton(self.tab)
        self.pushButton_ActKey.setObjectName("pushButton_ActKey")
        self.gridLayout_3.addWidget(self.pushButton_ActKey, 4, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 8, 0, 1, 1)
        self.label_LicenseAvaliable = QtWidgets.QLabel(self.tab)
        self.label_LicenseAvaliable.setText("")
        self.label_LicenseAvaliable.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LicenseAvaliable.setObjectName("label_LicenseAvaliable")
        self.gridLayout_3.addWidget(self.label_LicenseAvaliable, 5, 1, 1, 1)
        self.lineEdit_License = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_License.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_License.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_License.setObjectName("lineEdit_License")
        self.gridLayout_3.addWidget(self.lineEdit_License, 1, 1, 1, 1)
        self.pushButton_LicenseCheck = QtWidgets.QPushButton(self.tab)
        self.pushButton_LicenseCheck.setObjectName("pushButton_LicenseCheck")
        self.gridLayout_3.addWidget(self.pushButton_LicenseCheck, 5, 2, 1, 1)
        self.pushButton_EmulatorLocation = QtWidgets.QPushButton(self.tab)
        self.pushButton_EmulatorLocation.setObjectName("pushButton_EmulatorLocation")
        self.gridLayout_3.addWidget(self.pushButton_EmulatorLocation, 8, 2, 1, 1)
        self.pushButton_DownloadEmulator = QtWidgets.QPushButton(self.tab)
        self.pushButton_DownloadEmulator.setObjectName("pushButton_DownloadEmulator")
        self.gridLayout_3.addWidget(self.pushButton_DownloadEmulator, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_PhoneNumber = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_PhoneNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PhoneNumber.setObjectName("lineEdit_PhoneNumber")
        self.gridLayout_3.addWidget(self.lineEdit_PhoneNumber, 4, 1, 1, 1)
        self.pushButton_BuyKeys = QtWidgets.QPushButton(self.tab)
        self.pushButton_BuyKeys.setObjectName("pushButton_BuyKeys")
        self.gridLayout_3.addWidget(self.pushButton_BuyKeys, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.textEdit_News = QtWidgets.QTextEdit(self.tab)
        self.textEdit_News.setEnabled(True)
        self.textEdit_News.setObjectName("textEdit_News")
        self.verticalLayout_2.addWidget(self.textEdit_News)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 8, 0, 1, 1)
        self.comboBox_RandomStrLenComment = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_RandomStrLenComment.setObjectName("comboBox_RandomStrLenComment")
        self.comboBox_RandomStrLenComment.addItem("")
        self.comboBox_RandomStrLenComment.addItem("")
        self.comboBox_RandomStrLenComment.addItem("")
        self.comboBox_RandomStrLenComment.addItem("")
        self.comboBox_RandomStrLenComment.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_RandomStrLenComment, 17, 3, 1, 1)
        self.checkBox_AutoMessage = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoMessage.setObjectName("checkBox_AutoMessage")
        self.gridLayout_2.addWidget(self.checkBox_AutoMessage, 18, 0, 1, 1)
        self.comboBox_CommentType = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_CommentType.setObjectName("comboBox_CommentType")
        self.comboBox_CommentType.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_CommentType, 14, 3, 1, 1)
        self.textEdit_Message = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_Message.setObjectName("textEdit_Message")
        self.gridLayout_2.addWidget(self.textEdit_Message, 18, 2, 1, 2)
        self.checkBox_InsertStrAfterComment = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_InsertStrAfterComment.setObjectName("checkBox_InsertStrAfterComment")
        self.gridLayout_2.addWidget(self.checkBox_InsertStrAfterComment, 17, 2, 1, 1)
        self.comboBox_WatchTime = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_WatchTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_WatchTime.setObjectName("comboBox_WatchTime")
        self.comboBox_WatchTime.addItem("")
        self.comboBox_WatchTime.addItem("")
        self.comboBox_WatchTime.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_WatchTime, 8, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.textEdit_Comment = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_Comment.setObjectName("textEdit_Comment")
        self.gridLayout_2.addWidget(self.textEdit_Comment, 15, 2, 1, 2)
        self.comboBox_RandomStrLenMessage = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_RandomStrLenMessage.setObjectName("comboBox_RandomStrLenMessage")
        self.comboBox_RandomStrLenMessage.addItem("")
        self.comboBox_RandomStrLenMessage.addItem("")
        self.comboBox_RandomStrLenMessage.addItem("")
        self.comboBox_RandomStrLenMessage.addItem("")
        self.comboBox_RandomStrLenMessage.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_RandomStrLenMessage, 19, 3, 1, 1)
        self.pushButton_InitDevice = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_InitDevice.setObjectName("pushButton_InitDevice")
        self.gridLayout_2.addWidget(self.pushButton_InitDevice, 3, 0, 1, 1)
        self.checkBox_AutoComment = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoComment.setObjectName("checkBox_AutoComment")
        self.gridLayout_2.addWidget(self.checkBox_AutoComment, 15, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 14, 2, 1, 1)
        self.checkBox_InsertStrAfterMessage = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_InsertStrAfterMessage.setObjectName("checkBox_InsertStrAfterMessage")
        self.gridLayout_2.addWidget(self.checkBox_InsertStrAfterMessage, 19, 2, 1, 1)
        self.pushButton_Run = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.gridLayout_2.addWidget(self.pushButton_Run, 3, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBox_DeviceList = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_DeviceList.setObjectName("comboBox_DeviceList")
        self.gridLayout_2.addWidget(self.comboBox_DeviceList, 5, 2, 1, 1)
        self.checkBox_RestartDouyin = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_RestartDouyin.setChecked(True)
        self.checkBox_RestartDouyin.setObjectName("checkBox_RestartDouyin")
        self.gridLayout_2.addWidget(self.checkBox_RestartDouyin, 6, 2, 1, 1)
        self.checkBox_AutoInitial = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoInitial.setChecked(True)
        self.checkBox_AutoInitial.setObjectName("checkBox_AutoInitial")
        self.gridLayout_2.addWidget(self.checkBox_AutoInitial, 6, 0, 1, 1)
        self.checkBox_EnableMultiDevices = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_EnableMultiDevices.setEnabled(False)
        self.checkBox_EnableMultiDevices.setCheckable(True)
        self.checkBox_EnableMultiDevices.setChecked(True)
        self.checkBox_EnableMultiDevices.setObjectName("checkBox_EnableMultiDevices")
        self.gridLayout_2.addWidget(self.checkBox_EnableMultiDevices, 5, 3, 1, 1)
        self.comboBox_WorkMode = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_WorkMode.setObjectName("comboBox_WorkMode")
        self.comboBox_WorkMode.addItem("")
        self.comboBox_WorkMode.addItem("")
        self.comboBox_WorkMode.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_WorkMode, 4, 2, 1, 1)
        self.checkBox_DownVideo = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_DownVideo.setObjectName("checkBox_DownVideo")
        self.gridLayout_2.addWidget(self.checkBox_DownVideo, 7, 3, 1, 1)
        self.checkBox_AutoAddFriend = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoAddFriend.setChecked(True)
        self.checkBox_AutoAddFriend.setObjectName("checkBox_AutoAddFriend")
        self.gridLayout_2.addWidget(self.checkBox_AutoAddFriend, 7, 2, 1, 1)
        self.checkBox_AutoAwesome = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_AutoAwesome.setChecked(True)
        self.checkBox_AutoAwesome.setObjectName("checkBox_AutoAwesome")
        self.gridLayout_2.addWidget(self.checkBox_AutoAwesome, 7, 0, 1, 1)
        self.checkBox_Cnt = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_Cnt.setObjectName("checkBox_Cnt")
        self.gridLayout_2.addWidget(self.checkBox_Cnt, 6, 3, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_OnlinePeople = QtWidgets.QLabel(Dialog)
        self.label_OnlinePeople.setText("")
        self.label_OnlinePeople.setObjectName("label_OnlinePeople")
        self.gridLayout.addWidget(self.label_OnlinePeople, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textEdit_Print = QtWidgets.QTextEdit(Dialog)
        self.textEdit_Print.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit_Print.setAcceptDrops(True)
        self.textEdit_Print.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_Print.setObjectName("textEdit_Print")
        self.verticalLayout.addWidget(self.textEdit_Print)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_SaveLog = QtWidgets.QPushButton(Dialog)
        self.pushButton_SaveLog.setObjectName("pushButton_SaveLog")
        self.horizontalLayout_2.addWidget(self.pushButton_SaveLog)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_ClearLog = QtWidgets.QPushButton(Dialog)
        self.pushButton_ClearLog.setObjectName("pushButton_ClearLog")
        self.horizontalLayout_2.addWidget(self.pushButton_ClearLog)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "[耐诺网络]抖音大师 v1.3"))
        self.pushButton_StartEmulator.setText(_translate("Dialog", "启动模拟器"))
        self.label_2.setText(_translate("Dialog", "手机号码"))
        self.pushButton_VisitHome.setText(_translate("Dialog", "官方网站"))
        self.pushButton_ActKey.setText(_translate("Dialog", "激活"))
        self.label_20.setText(_translate("Dialog", "第一步"))
        self.label_18.setText(_translate("Dialog", "有效期"))
        self.label_3.setText(_translate("Dialog", "第二步"))
        self.lineEdit_License.setText(_translate("Dialog", "d0ced2fa-496d-11e8-869d-d46d6d9832e8"))
        self.pushButton_LicenseCheck.setText(_translate("Dialog", "检查"))
        self.pushButton_EmulatorLocation.setText(_translate("Dialog", "路径设置"))
        self.pushButton_DownloadEmulator.setText(_translate("Dialog", "下载模拟器"))
        self.label_4.setText(_translate("Dialog", "序列号"))
        self.pushButton_BuyKeys.setText(_translate("Dialog", "购买"))
        self.textEdit_News.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">官方消息</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\">请认准官方网站为http://douyin.craftor.org</p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">当前版本</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">v1.3   [2018-05-29]</li>\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">支持多开</li></ul></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "初始化"))
        self.label_5.setText(_translate("Dialog", "每段视频观看时间："))
        self.comboBox_RandomStrLenComment.setItemText(0, _translate("Dialog", "4"))
        self.comboBox_RandomStrLenComment.setItemText(1, _translate("Dialog", "5"))
        self.comboBox_RandomStrLenComment.setItemText(2, _translate("Dialog", "6"))
        self.comboBox_RandomStrLenComment.setItemText(3, _translate("Dialog", "7"))
        self.comboBox_RandomStrLenComment.setItemText(4, _translate("Dialog", "8"))
        self.checkBox_AutoMessage.setText(_translate("Dialog", "自动私信"))
        self.comboBox_CommentType.setItemText(0, _translate("Dialog", "随机"))
        self.textEdit_Message.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">互粉谢谢^_^</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">加个关注呗~</p></body></html>"))
        self.checkBox_InsertStrAfterComment.setText(_translate("Dialog", "结尾插入随机符长度"))
        self.comboBox_WatchTime.setCurrentText(_translate("Dialog", "0-5（秒）"))
        self.comboBox_WatchTime.setItemText(0, _translate("Dialog", "0-5（秒）"))
        self.comboBox_WatchTime.setItemText(1, _translate("Dialog", "5-10（秒）"))
        self.comboBox_WatchTime.setItemText(2, _translate("Dialog", "10-15（秒）"))
        self.label.setText(_translate("Dialog", "工作模式："))
        self.textEdit_Comment.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">太棒了！</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">666666</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">厉害了</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">人才啊</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">貌似会火</p></body></html>"))
        self.comboBox_RandomStrLenMessage.setItemText(0, _translate("Dialog", "4"))
        self.comboBox_RandomStrLenMessage.setItemText(1, _translate("Dialog", "5"))
        self.comboBox_RandomStrLenMessage.setItemText(2, _translate("Dialog", "6"))
        self.comboBox_RandomStrLenMessage.setItemText(3, _translate("Dialog", "7"))
        self.comboBox_RandomStrLenMessage.setItemText(4, _translate("Dialog", "8"))
        self.pushButton_InitDevice.setText(_translate("Dialog", "初始化模拟器"))
        self.checkBox_AutoComment.setText(_translate("Dialog", "自动评论"))
        self.label_8.setText(_translate("Dialog", "内容："))
        self.checkBox_InsertStrAfterMessage.setText(_translate("Dialog", "结尾插入随机符长度"))
        self.pushButton_Run.setText(_translate("Dialog", "开始"))
        self.label_6.setText(_translate("Dialog", "设备列表："))
        self.checkBox_RestartDouyin.setText(_translate("Dialog", "自动重启抖音"))
        self.checkBox_AutoInitial.setText(_translate("Dialog", "自动初始化"))
        self.checkBox_EnableMultiDevices.setText(_translate("Dialog", "多开"))
        self.comboBox_WorkMode.setItemText(0, _translate("Dialog", "默认模式"))
        self.comboBox_WorkMode.setItemText(1, _translate("Dialog", "只刷关注用户"))
        self.comboBox_WorkMode.setItemText(2, _translate("Dialog", "只刷附近用户"))
        self.checkBox_DownVideo.setText(_translate("Dialog", "自动下载视频"))
        self.checkBox_AutoAddFriend.setText(_translate("Dialog", "自动加好友"))
        self.checkBox_AutoAwesome.setText(_translate("Dialog", "自动点赞"))
        self.checkBox_Cnt.setText(_translate("Dialog", "显示计数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "一键操作"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">准备工作：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1、下载、安装【安卓模拟器】</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2、运行【安卓模拟器】，设置分辨率为800x600，并开启软键盘，然后重启</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3、在【安卓模拟器】的市场中搜索“抖音”，并进行安装；或在软件中点击【下载抖音】到Windows中，然后再拖拽到安卓模拟器中</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4、点击【初始化模拟器】，成功后模拟器中会弹出一个网页，表示安装成功；否则，尝试重启模拟器，再尝试点击</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5、初始化模拟器完成后，到【模拟器里的安卓系统中-&gt;设置】中（注意不是模拟器自身的设置），将默认输入法设置为【FastInputIME】，否则无法实现评论和私信</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">刷抖音注意事项：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1、每次间隔的时间尽量不要太短，建议10秒以上（目前还没有测到抖音封号的边界条件，所以尽量还是保守一点比较好）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2、点击【开始/停止】会有点卡，请耐心等待一下</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3、在【开始】之后，【自动点赞】、【自动加好友】、【自动下载视频】、【自动评论】、【自动私信】、【显示计数】这些功能是随时可以开关的，不需要停止</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4、【自动评论】、【自动私信】还没有测到边界条件，目前可以不加随机字符。</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "操作说明"))
        self.label_9.setText(_translate("Dialog", "当前在线人数："))
        self.pushButton_SaveLog.setText(_translate("Dialog", "保存日志"))
        self.pushButton_ClearLog.setText(_translate("Dialog", "清除"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

